version: 2.1
orgs:
  macos: circleci/macos@2.4.1
jobs:
  adhoc:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: upload_release
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - adhoc:
          filters:
            branches:
              only: cicd
