default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload Release to App Store"
  lane :upload_release do
    xcversion(version: "15.4")

    match

    asc_key_content = ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    asc_issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    asc_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]
    api_key = app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content
    )

    increment_build_number(
      build_number: app_store_build_number(
        api_key: api_key,
        initial_build_number: 7,
        version: get_version_number(xcodeproj: "Test SmartSpectra SDK.xcodeproj"),
        live: false,
      ) + 1,
    )

    # Set up Distribution code signing and build the app
    gym(scheme: "Test SmartSpectra SDK", export_method: "app-store", xcargs: "-allowProvisioningUpdates")

    upload_to_testflight(
      distribute_external: false,
      notify_external_testers: false,
      changelog: "Hello World CI/CD"
    )
  end
end
