default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload Release to App Store"
  lane :upload_release do
    # Get the version number from the project and check against
    # the latest build already available on App Store Connect, then
    # increase the build number by 1. If no build is available
    # for that version, then start at 1
    increment_build_number(
      build_number: app_store_build_number(
        initial_build_number: 7,
        version: get_version_number(xcodeproj: "Test SmartSpectra SDK.xcodeproj"),
        live: false,
	username: "bryce@presagesecurity.com",
	app_identifier: "com.presage.smart.SDK.example.Example"
      ) + 1,
    )
    # Set up Distribution code signing and build the app
    get_certificates(username: "bryce@presagesecurity.com")
    get_provisioning_profile(username: "bryce@presagesecurity.com", app_identifier: "com.presage.smart.SDK.example.Example")
    gym(scheme: "Test SmartSpectra SDK")
    # Upload the binary to App Store Connect
    #app_store_connect_api_key
    #match
    upload_to_testflight(
      username: "bryce@presagesecurity.com",
      team_id: "54D6QF28QA",
      distribute_external: false,
      notify_external_testers: false,
      app_identifier: "com.presage.smart.SDK.example.Example",
      changelog: "Hello World CI/CD"
    )
  end
end
