default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload Release to App Store"
  lane :upload_release do
    match
    increment_build_number(
      build_number: app_store_build_number(
        initial_build_number: 7,
        version: get_version_number(xcodeproj: "Test SmartSpectra SDK.xcodeproj"),
        live: false,
      ) + 1,
    )
    # Set up Distribution code signing and build the app
    gym(scheme: "Test SmartSpectra SDK")
    # Upload the binary to App Store Connect
    #app_store_connect_api_key
    upload_to_testflight(
      distribute_external: false,
      notify_external_testers: false,
      changelog: "Hello World CI/CD"
    )
  end
end
